import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const albertBold = localFont({
  src: "./fonts/FSAlbertArabic-Bold.ttf",
  variable: "--font-albert-bold",
  weight: "100 900",
});
const albertReg = localFont({
  src: "./fonts/FSAlbertArabic-Regular.ttf",
  variable: "--font-albert-reg",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${albertBold.variable} ${albertReg.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
